name: Handle issue label events
on:
  issues:
    types: [labeled, unlabeled]
jobs:
  call-workflow:
    name: Call shared workflow
    uses: learningequality/.github/.github/workflows/issue-label.yml@main
    secrets:
      LE_BOT_APP_ID: ${{ secrets.LE_BOT_APP_ID }}
      LE_BOT_PRIVATE_KEY: ${{ secrets.LE_BOT_PRIVATE_KEY }}
